### PR TITLE
refactor!: Use latest SDK for flattened config stem

### PR DESCRIPTION
**Pull request by jim-wang-intel**
BREAKING CHANGE: location of service configuration in Consul changed; also required v3 module path upgrade

Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-gpio/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

1. Run EdgeX non-secure stack so Consul is running
1. Build the service locally make build
1. cd cmd
1. export EDGEX_SECURITY_SECRET_STORE=false; ./device-gpio -cp and 
verify that the service configuration is at http://localhost:8500/ui/dc1/kv/edgex/v3/

### CODE REVIEW

**Comment by jim-wang-intel** [comment]
cc: @ejlee3  @lenny-intel  please do reviewers and labelings as i don't have committer rights for device-related repos.

**Review by lenny-intel — CHANGES_REQUESTED** [review]
The Consul structure flattening is the breaking change, not the v3 modules.
Please update commit message and PR title to match this one: 
https://github.com/edgexfoundry/app-service-configurable/pull/491/commits/5c99e1cd132ccc19edbcd18e483be06a1f5b21fe

**Comment by jim-wang-intel** [comment]
> The Consul structure flattening is the breaking change, not the v3 modules. Please update commit message and PR title to match this one: [edgexfoundry/app-service-configurable@5c99e1c](https://github.com/edgexfoundry/app-service-configurable/commit/5c99e1cd132ccc19edbcd18e483be06a1f5b21fe)

@lenny-intel  changed

**Review by ejlee3 — APPROVED** [review]
LGTM. Tried it out and it works.

**Pull request merged**
