### PR TITLE
fix: Correct the service's port number

### PR DESCRIPTION
**Pull request by lenny-intel**
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-gpio/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Review by bnevis-i — APPROVED** [review]

**Comment by bnevis-i** [comment]
@lenny-intel Non-approving approval :-)

**Review by iain-anderson — APPROVED** [review]

**Comment by lenny-intel** [comment]
@farshidtz , FYI snap test is failing due to using the incorrect port number that this PR fixes.

**Review by farshidtz — COMMENTED** [review]
Are we changing the port for the 3.0 release? What is wrong with 59910?

**Comment by bnevis-i** [comment]
> Are we changing the port for the 3.0 release? What is wrong with 59910?

It is not the agreed-upon port https://docs.edgexfoundry.org/2.2/general/ServicePorts/

**Comment by farshidtz** [comment]
> > Are we changing the port for the 3.0 release? What is wrong with 59910?
> 
> It is not the agreed-upon port https://docs.edgexfoundry.org/2.2/general/ServicePorts/

The service has been released with port 59910, so I could say the documentation is wrong. Why don't we just change it in the documentation instead?

Even if we change the configuration (as with this PR), we still have to correct it in the documentation of previous releases.

Also, changing the port is definitely a BREAKING CHANGE.

**Comment by iain-anderson** [comment]
Just to clarify - documentation for all previous releases also states 59994 as the port
I keep a list of port allocations on the WG wiki page https://wiki.edgexfoundry.org/display/FA/Device+and+Device+SDK+Working+Group

**Comment by farshidtz** [comment]
So there are two options:

1. Change the service port (config, dockerfile) as done with this PR, plus:
    - Correct docs for 2.0, 2.1, 2.2, 2.3 to have 59910
    - Update tests to expect 59994 starting from 3.0
    - Flag it as a BREAKING CHANGE and add it to 3.0 migration guide 
 2. Change the port in docs
    - Change port from 59994 to 59910 in 2.0-2.3 as well as the main (to be 3.0) docs.
    - Change the port in wiki

Option 2 sounds simpler to me, both for the project maintainers and users.

**Comment by iain-anderson** [comment]
Oddly enough, compose-builder for Ireland supports adding `ds-gpio` but there was never a 2.0 release of this service :)

**Comment by iain-anderson** [comment]
At the WG meeting on 9th Jan it was agreed that we would keep 59910 as the port for this service and update the documentation and compose-builder accordingly. Closing this PR.

**Pull request closed without merging**
